### ISSUE TITLE
Object #<NodeList> has no method 'getAttribute'

### ISSUE THREAD

**Issue by SerbanC** [jackrugile/placeholdem#4]
Hi, I'm trying to implement Placeholdem but I get this error on line:

```
PE.placeholder = PE.elem.getAttribute( 'placeholder' );
```

I can duplicate it by trying to get the placeholder attribute of my querySelectorAll results in the console:

```
var elem = document.querySelectorAll("[placeholder]");
elem.getAttribute('placeholder');
TypeError: Object #<NodeList> has no method 'getAttribute'
```

If I change the second line to 

```
elem[0].getAttribute('placeholder');
```

it returns the placeholder string correctly.

On the demo site if I execute

```
Placeholdem( document.querySelectorAll( '[placeholder]' ) );
```

in the console I get the same error.

Am I missing something?

**Comment by jackrugile** [comment]
Hey, I am having trouble reproducing that error. There is a check on the init() method that checks whether a single element or group of elements was passed in, and then handles it correctly:

``` js
P.elems = [];
if( elems.length ) {
    for( var i = 0 ; i < elems.length; i++ ) {
        P.elems.push( new P.PlaceholdemElem( elems[ i ] ) );
    }
} else {
    P.elems.push( new P.PlaceholdemElem( elems ) );
}
```

So, the tests you isolated should already be handled within the plugin.

However, when you run that line of code in the console again on the demo site, that should be the error you get, as I haven't handled the error of passing in invalid elements, or basically no elements. The placeholders get removed after the plugin has already run, so that returns nothing if you run it again in the console on the demo site.

So, just to clarify, are you adding the `placeholder="text"` attribute to your inputs and textareas? If not, that selector won't work. If that is the case, that will fix it, and I will add in better checking for empty elements.

**Comment by SerbanC** [comment]
Yes, it works fine :) I took your instructions too literally and wasn't waiting until document.ready to initialize. Thanks

**Comment by SerbanC** [comment]
New problem though :)
I want placeholdem available throughout my website so I put it in a global JS file. Now on pages that don't have any element with the [placeholder] attribute I get the same error from the title because the query returns an empty array. This is a problem because any JS after it will no longer run. I fixed it on my project by placing the placeholdem init line at the very end, but a fix would be nice. Thanks

**Comment by jackrugile** [comment]
You're absolutely right, this is a huge oversight! I will fix it as soon as possible. Still looking into the best way verify whether the argument passed in is an element or group of elements.

Sorry for the inconvenience, glad you got it working for your project though. Thanks for the heads up!
