### ISSUE TITLE
Add onDeleteComplete and onRestoreComplete callback options

### ISSUE THREAD

**Issue by jackrugile** [jackrugile/placeholdem#7]

**Comment by farinspace** [comment]
+1

perhaps also adding: onDeleteStart, onRestoreStart ...

my use-case is the following: I would like to have the input css color set as Y when the placeholder is in place, and then set as Z when having user input. 

Having "onRestoreStart" would be useful because this would would allow me to switch colors before the animation begins (and not on-complete, after its been fully restored).

Callback naming suggestions:

onBeforeDelete, 
onAfterDelete (onDeleteComplete)
onBeforeRestore, 
onAfterRestore  (onRestoreComplete)

**Comment by jackrugile** [comment]
Just wanted to give a heads up that this plugin is officially inactive. I've updated the readme to reflect that. Thanks for using the plugin and I apologize for any inconvenience.

> This project is no longer being developed or maintained. The effect this plugin gives is visually appealing, but it's a bad practice in terms of usability and accessibility. On top of that, manipulating the values of different HTML5 input types directly has a lot of issues (text, email, number, search, etc.). I suggest using an alternative styling for labels and placeholders, such as Floating Labels.
