### ISSUE TITLE
Placeholder shouldn't alter value

### ISSUE THREAD

**Issue by andrewtch** [jackrugile/placeholdem#9]
Subj; please do not remove "placeholder" attribute and do not alter "value" of element (or at least set something like data-original-placeholder, so it's possible to find out if the field is changed at all). The current behavior makes placeholder senseless and breaks semantics.

**Comment by jackrugile** [comment]
Hey, I completely agree about saving the original placeholder somehow. I was removing the original placeholder attribute because it was messing up the display with its default behavior. I think something like data-placeholder would work great.

As for not altering the value of the element, I'm not sure how I'd achieve the caret animation without changing the value itself. Do you have any idea for that?

Thank you for your input!

**Comment by andrewtch** [comment]
@jackrugile , placeholders can be animated using css3: https://coderwall.com/p/hp9dzg

If it's not possible to create a good looking animation, you should override .val() for these Placeholdem elements (so they return '' if there's no change) and bind to parent form, if any, cleaning up values on submit.

Poke me tomorrow, I'll take a look on css animations )
